version: '3.9'

services:
  db:
    image: mysql:8.0.33
    container_name: student_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_management
    ports:
      - "3355:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: student-management-app:latest
    container_name: student_management_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3355/student_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db_data: {}